### ISSUE TITLE
Reactivate USBProg

### ISSUE THREAD

**Issue by m9aertner** [Solartraveler/ps2toUsb#1]
Hello, nice work! Thanks for sharing!

I remembered that I had an old USBProg 3.1 lying around in a box and thought about re-activating it to give your PS/2 converter a try.

Alas, my unit seems to be malfunctioning. More or less. Flashing the base program again seems to work (via avrdude and an Arduino-based ISP prgrammer). But when connecting it to my PC (Win10), it does not show up properly in control panel. I do have the Jungo driver installed, and under that "WinDriver" is also available.

Alas, the newly flashed unit  shows up as "Other Devices / usbprogBase mode". With exclamation mark. I recall it should show up as some "mkII" programmer under Jungo? I guess it's not the right HEX file that I used?!

Could you please read out and share the `usbprog_base.hex` file, from your **working** unit? And the fuse settings (L, H)? Unfortunately, Benedikt Sauter's USBProg home page has gone by now and I am not sure [https://github.com/ykhalyavin/usbprog](https://github.com/ykhalyavin/usbprog) is the _latest_ (or better _matching_) code...

    avrdude: Version 6.3
    ...
    avrdude: Device signature = 0x1e9502 (probably m32)
    ...
    avrdude: safemode: hfuse reads as D8
    avrdude: safemode: Fuses OK (E:FF, H:D8, L:E0)

Reading out the HEX file with something like

    avrdude -v -p m32 -c stk500v1 -P COM4 -b 19200 -U flash:r:usbprog_base.hex:i

**Comment by Solartraveler** [comment]
Hello,
thanks for your interests in this project. I was too lazy to connect an other programmer, but seems like I wrote it down in a file for future reference back 2008 :)
```
Fuses for ATMEGA32 in USBprog:
Low: 10100000
High: 11011000
```
So the only difference to your fuses is the enabled brown-out detector on mine. Yours are the ones described in the original manual.
All usbprog_base.hex i found on my PC have the md5sum 59bbfac108f2e0d6f38e6cf85ca9a36d, including the one found in my  svn archive.
So far, this is the bootloader, which starts when the UART RX and TX are connected together, mine then reports the same under Linux:
```
[10011.654267] usb 3-3.3: New USB device found, idVendor=1781, idProduct=0c62, bcdDevice= 0.00
[10011.654271] usb 3-3.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[10011.654273] usb 3-3.3: Product: usbprogBase Mode
[10011.654275] usb 3-3.3: Manufacturer: USBprog EmbeddedProjects
```
mkII would be one of the firmware running once downloaded over the usbprogBase bootloader. Some of the firmware (not mine) were able "magically" jump to the bootloader, so someone might never have noticed the usbprogBase bootloader. The usbprogBase bootloader lets the LED flash 2x two short pulses, 1x pause, then repeat the cycle.

The RX<->TX connection detection seems not to work perfect, because I always ended up in a "not bootloader, not main program" state when I had a MAX232 level converter connected to the TX pin, but the MAX232 not powered.

So I think you now you need to get the couterpart of the bootloader running. Or just remove (other fuse settings) the bootloader and flash my file (there is a ready to be used .hex artifact by github - I must admit I never tested it, nor did I do any tests without the magic bootloader in place).

Let be know if this helps.

**Comment by m9aertner** [comment]
Thanks for sharing the MD5! I have the very same file, so _that's_ not the problem. Will continue checking.

https://raw.githubusercontent.com/ykhalyavin/usbprog/master/usbprog_base/firmware/usbprog_base.hex

Actually, I am sorry to have bothered you with this on this chanel, since this certainly is a problem **entirely on my side** and has nothing to do with your fine project! Hence closing this issue.

(Will add a note when I get it to work, eventually)
